### ISSUE TITLE
怎么可以login

### ISSUE THREAD

**Issue by Coande** [qihaiyan/jwt-boot-auth#1]
请问没有显式配置 controller ，为什么可以 login ，是 security 有个默认 login 的 controller 吗？ username 和
 password 两个字段是固定的吗？我自己创建了个项目，不知道为什么 permitAll 后都会403。

**Comment by qihaiyan** [comment]
是的，login是springsecurity自带的默认登录接口，具体可以看以下springsecurity的官方文档。

**Comment by Coande** [comment]
谢谢回复。
